### PR TITLE
Fix/sign in with existing email error

### PR DESCRIPTION
**Pull request by Alec-Watson**
Changes to how the user is notified of incorrect sign-up
image
image

### CODE REVIEW

**Comment by JFMalan** [comment]
Please describe your PR better, add some images of the error popup

**Comment by JFMalan** [comment]
Why not add red text like we do for login failures, keep it consistent

**Comment by Alec-Watson** [comment]
> Why not add red text like we do for login failures, keep it consistent

See the new imgs for the change

**Review by JFMalan — APPROVED** [review]
Very lekker 👍

**Pull request merged**
